# Generated by Django 2.0.7 on 2021-01-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_auto_20210109_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='text',
            field=models.CharField(default='empty string', max_length=50),
            preserve_default=False,
        ),
    ]
