# Generated by Django 2.0.7 on 2021-01-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_geeksmodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashcardsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontside', models.CharField(max_length=24)),
                ('backside', models.CharField(max_length=24)),
                ('answer', models.CharField(max_length=44)),
            ],
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='text',
        ),
    ]
