# Generated by Django 2.0.7 on 2021-01-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_auto_20210116_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
