# Generated by Django 2.0.7 on 2021-01-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_delete_geeksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnwantedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=24)),
                ('second', models.CharField(max_length=24)),
                ('blah', models.CharField(max_length=44)),
            ],
        ),
    ]
